### ISSUE TITLE
Error while running sample/llm_sample.py

### ISSUE THREAD

**Issue by egcash** [MIDORIBIN/langchain-gpt4free#2]
Traceback (most recent call last):
  File "/root/langchain-gpt4free/sample/llm_sample.py", line 18, in <module>                                                            main()

File "/root/langchain-gpt4free/sample/llm_sample.py", line 8, in main                                                                 llm: LLM = G4FLLM(

File "/root/tempo-env/lib/python3.10/site-packages/langchain/load/serializable.py", line 74, in __init__                              super().__init__(**kwargs)                                      

File "/root/tempo-env/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__                                        raise validation_error                                        pydantic.v1.error_wrappers.ValidationError: 1 validation error for G4FLLM                                                           provider                                                            instance of module expected (type=type_error.arbitrary_type; expected_arbitrary_type=module)

**Comment by egcash** [comment]
I performed all the steps given in README,still facing this 👆👆

**Comment by egcash** [comment]
I performed all the steps given in README,still facing this error.

**Comment by MIDORIBIN** [comment]
@egcash 
The update of gpt4free is affecting.
Fix it immediately.

**Comment by egcash** [comment]
What should I do??
Can you explain in Little more detail?

**Comment by MIDORIBIN** [comment]
@egcash 
Fixed.
If you find any more problems, please report them to us.

**Comment by egcash** [comment]
@MIDORIBIN nothing you changed!!!

I tried with g4f v0.0.1.9

And it works!!!

**Comment by MIDORIBIN** [comment]
@egcash 
The following commit fixes the problem.
If you reinstalled and the problem has not been resolved, please report the error in detail.

https://github.com/MIDORIBIN/langchain-gpt4free/commit/a6da9a5d5f56827174620498c82bc16efad257c7

**Comment by egcash** [comment]
Fixed!
