### ISSUE TITLE
TypeError: '_InterfaceMetaClass' object is not iterable

### ISSUE THREAD

**Issue by bluedolphi** [MIDORIBIN/langchain-gpt4free#6]
Traceback (most recent call last):
  File "E:\my program\python\aiyz_dabai_backen\g4f_llm\WorkOrder_Processing_Robot.py", line 1, in <module>
    from g4f import Provider, models
  File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\g4f\__init__.py", line 2, in <module>
    from .          import models
  File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\g4f\models.py", line 3, in <module>
    from .Provider import Bard, BaseProvider, GetGpt, H2o, Liaobots, Vercel, Equing
  File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\g4f\Provider\__init__.py", line 21, in <module>
    from .OpenaiChat    import OpenaiChat
  File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\g4f\Provider\OpenaiChat.py", line 3, in <module>
    from curl_cffi.requests import AsyncSession
  File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\curl_cffi\requests\__init__.py", line 19, in <module>
    from .session import AsyncSession, BrowserType, Session
  File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\curl_cffi\requests\session.py", line 19, in <module>
    import gevent
  File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\gevent\__init__.py", line 71, in <module>
    from gevent._config import config
  File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\gevent\_config.py", line 730, in <module>
    Loop().get()
  File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\gevent\_config.py", line 151, in get
    self.value = self.validate(self._default())
  File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\gevent\_config.py", line 259, in validate
    return self._import_one_of([self.shortname_map.get(x, x) for x in value])
  File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\gevent\_config.py", line 230, in _import_one_of
    return self._import_one(item)
  File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\gevent\_config.py", line 248, in _import_one
    module = importlib.import_module(module)
  File "D:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\gevent\libuv\loop.py", line 13, in <module>
    from zope.interface import implementer
  File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\zope\interface\__init__.py", line 53, in <module>
    from zope.interface.interface import Interface
  File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\zope\interface\interface.py", line 682, in <module>
    class InterfaceClass(_InterfaceClassBase):
  File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\zope\interface\interface.py", line 641, in __new__
    kind = type.__new__(cls, name, bases, attrs)
TypeError: '_InterfaceMetaClass' object is not iterable

**Comment by MIDORIBIN** [comment]
@bluedolphi 
Thanks for the report.
Please show me the code you ran.

**Comment by goldeneave** [comment]
> Traceback (most recent call last): File "E:\my program\python\aiyz_dabai_backen\g4f_llm\WorkOrder_Processing_Robot.py", line 1, in from g4f import Provider, models File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\g4f__init__.py", line 2, in from . import models File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\g4f\models.py", line 3, in from .Provider import Bard, BaseProvider, GetGpt, H2o, Liaobots, Vercel, Equing File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\g4f\Provider__init__.py", line 21, in from .OpenaiChat import OpenaiChat File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\g4f\Provider\OpenaiChat.py", line 3, in from curl_cffi.requests import AsyncSession File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\curl_cffi\requests__init__.py", line 19, in from .session import AsyncSession, BrowserType, Session File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\curl_cffi\requests\session.py", line 19, in import gevent File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\gevent__init__.py", line 71, in from gevent._config import config File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\gevent_config.py", line 730, in Loop().get() File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\gevent_config.py", line 151, in get self.value = self.validate(self._default()) File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\gevent_config.py", line 259, in validate return self._import_one_of([self.shortname_map.get(x, x) for x in value]) File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\gevent_config.py", line 230, in _import_one_of return self._import_one(item) File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\gevent_config.py", line 248, in _import_one module = importlib.import_module(module) File "D:\Python310\lib\importlib__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\gevent\libuv\loop.py", line 13, in from zope.interface import implementer File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\zope\interface__init__.py", line 53, in from zope.interface.interface import Interface File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\zope\interface\interface.py", line 682, in class InterfaceClass(_InterfaceClassBase): File "E:\my program\python\aiyz_dabai_backen\venv\lib\site-packages\zope\interface\interface.py", line 641, in **new** kind = type.**new**(cls, name, bases, attrs) TypeError: '_InterfaceMetaClass' object is not iterable

did you solve the problem, I got the same when I deploy dify framework
